services:
  - type: web
    name: indexgen-backend
    env: node
    buildCommand: apt-get update && apt-get install -y poppler-utils && npm install
    startCommand: node server.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false
